"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys, os

file_root = "/Users/laurencess/_GELATINDESIGN/Python/Ludum-Dare-24-Evolution/"

DATA_FILES = []
for files in os.listdir(file_root + 'sprites/enemies/'):
	f1 = file_root + 'sprites/enemies/' + files
	if os.path.isfile(f1):
		f2 = 'sprites/enemies', [f1]
		DATA_FILES.append(f2)

for files in os.listdir(file_root + 'sprites/friendlies/'):
	f1 = file_root + 'sprites/friendlies/' + files
	if os.path.isfile(f1):
		f2 = 'sprites/friendlies', [f1]
		DATA_FILES.append(f2)

for files in os.listdir(file_root + 'sprites/player/'):
	f1 = file_root + 'sprites/player/' + files
	if os.path.isfile(f1):
		f2 = 'sprites/player', [f1]
		DATA_FILES.append(f2)

for files in os.listdir(file_root + 'sounds/'):
	f1 = file_root + 'sounds/' + files
	if os.path.isfile(f1):
		f2 = 'sounds', [f1]
		DATA_FILES.append(f2)

for files in os.listdir(file_root + 'fonts/'):
	f1 = file_root + 'fonts/' + files
	if os.path.isfile(f1):
		f2 = 'fonts', [f1]
		DATA_FILES.append(f2)

DATA_FILES.append(file_root + "preferences.txt")

APP = ['main.py']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
